### ISSUE TITLE
Improve UI of the app

### ISSUE THREAD

**Issue by sunilsj99** [sunilsj99/Basic-News-App-#1]
send the pull request by creating a new branch

**Comment by sunilsj99** [comment]
@Gh05d  Yes !! If you want you can work on it.

**Comment by sterjoski** [comment]
I'd like to work on this if it's available.

**Comment by sunilsj99** [comment]
Please , work on it  !! @sterjoski

**Comment by aemc** [comment]
I would suggest using Material UI w/ React.

**Comment by AlexB801** [comment]
Is this still available for a possible redesign?

**Comment by sunilsj99** [comment]
@AlexB801 already there are so many PR's so I am sorry , but if you want to do something you can go through the api documentation https://newsapi.org/docs and could suggest some functionality improvements!!
